name = "syncinema-backend"
main = "src/index.ts"
compatibility_date = "2024-11-20"
compatibility_flags = ["nodejs_compat"]

[vars]
ENV = "production"

[[durable_objects.bindings]]
name = "ROOM_DO"
class_name = "RoomDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]

[observability]
enabled = true
